--- #YAML:1.0
name:               TwitShell
version:            4.06
abstract:           Command-line microblogging client.
author:
    - Alessandro Ghedini <al3xbio@gmail.com>
license:            GPLv3
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Curses:               0
    DateTime::Format::HTTP:  0
    Getopt::Long:         0
    HTTP::Request::Common:  0
    JSON:                 0
    LWP::UserAgent:       0
    Time::Out:            0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
